# Deploy OpenVPN server using Docker
version: '3.8'

# Define common configurations as YAML anchors
x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: 3

x-restart-policy: &default-restart
  restart: unless-stopped

# Combined defaults for all services
x-defaults: &defaults
  <<: *default-logging
  <<: *default-restart

# Environment defaults for OpenVPN
x-openvpn-environment: &openvpn-env
  # EasyRSA settings
  EASYRSA_BATCH: 1
  EASYRSA_REQ_CN: OpenVPN CA
  # OpenVPN core settings
  OVPN_SERVER: 10.20.0.0/24
  OVPN_DNS: 8.8.8.8,8.8.4.4
  OVPN_CLIENT_TO_CLIENT: 1
  OVPN_DUPLICATE_CN: 1
  DEBUG: 1

services:
  # Main OpenVPN service
  openvpn:
    <<: *defaults
    image: kylemanna/openvpn:latest
    container_name: openvpn-server
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv6.conf.all.forwarding: 1
      net.ipv6.conf.default.forwarding: 1
    ports:
      - 1194:1194/udp
      - 1195:1194/tcp  # Use port 1195 for TCP to avoid conflicts
      - 3005-3009:3005-3009/tcp  # Port forwarding range
    volumes:
      - openvpn_data:/etc/openvpn
      - ./client_configs:/etc/openvpn/clients:ro
      - ./setup.sh:/usr/local/bin/setup.sh:ro
    environment:
      <<: *openvpn-env
    # Use the external setup script
    entrypoint: ["/usr/local/bin/setup.sh"]
    healthcheck:
      test: [CMD-SHELL, "pgrep openvpn || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      openvpn_net:
        ipv4_address: 10.20.0.2

  # Admin Panel for OpenVPN
  openvpn-admin:
    <<: *defaults
    image: kylemanna/openvpn:2.4
    container_name: openvpn-admin-panel
    depends_on:
      - openvpn
    ports:
      - 8080:80
    volumes:
      - openvpn_data:/etc/openvpn:ro
    environment:
      OPENVPN_ADMIN_USERNAME: ${OPENVPN_ADMIN_USERNAME:-admin}
      OPENVPN_ADMIN_PASSWORD: ${OPENVPN_ADMIN_PASSWORD:-admin}
    command: [sh, -c, "echo 'Running admin interface' && sleep infinity"]
    networks:
      openvpn_net:
        ipv4_address: 10.20.0.3

  # Status Page for OpenVPN
  openvpn-status:
    <<: *defaults
    image: auspexeu/openvpn-status:latest
    container_name: openvpn-status-page
    depends_on:
      - openvpn
    ports:
      - 8081:80
    environment:
      OPENVPN_STATUS_LOG: /var/log/openvpn/status.log
      OPENVPN_MANAGEMENT_HOST: openvpn-server
      OPENVPN_MANAGEMENT_PORT: 7505
    networks:
      openvpn_net:
        ipv4_address: 10.20.0.4

# Network configuration
networks:
  openvpn_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/16
          gateway: 10.20.0.1

# Data persistence
volumes:
  openvpn_data:
    driver: local
