# Deploy OpenVPN server using Docker

services:
  # Main OpenVPN service
  openvpn:
    image: kylemanna/openvpn:2.4
    container_name: openvpn-server
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
      - "1195:1194/tcp"  # Use port 1195 for TCP to avoid conflicts
      - "3005-3009:3005-3009/tcp"  # Port forwarding range
    volumes:
      - openvpn_data:/etc/openvpn
      - ./client_configs:/etc/openvpn/clients:ro
    environment:
      - OVPN_DATA=/etc/openvpn
      - OVPN_SERVER=10.20.0.0/16
      - OVPN_PROTO=both  # Enable both UDP and TCP
      - OVPN_PORT=1194
      - OVPN_DNS=8.8.8.8,8.8.4.4
      - OVPN_MANAGEMENT=0.0.0.0 7505
      - OVPN_ROUTES=10.20.0.0/16
      - OVPN_NAT=true
      - OVPN_COMP_LZO=false
      - OVPN_CIPHER=AES-256-GCM
      - OVPN_TLS_VERSION_MIN=1.2
      - OVPN_TLS_CIPHER=TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384
      - OVPN_DUPLICATE_CN=true
      - OVPN_CLIENT_TO_CLIENT=true
      - DEBUG=1  # Enable debugging
    entrypoint: ["ovpn_run"]
    networks:
      openvpn_net:
        ipv4_address: 10.20.0.2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pidof", "openvpn"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Simple Admin Panel for OpenVPN
  openvpn-admin:
    image: kylemanna/openvpn:2.4
    container_name: openvpn-admin-panel
    depends_on:
      - openvpn
    ports:
      - "8080:80"
    volumes:
      - openvpn_data:/etc/openvpn:ro
    environment:
      - OPENVPN_ADMIN_USERNAME=${OPENVPN_ADMIN_USERNAME:-admin}
      - OPENVPN_ADMIN_PASSWORD=${OPENVPN_ADMIN_PASSWORD:-admin}
    command: ["sh", "-c", "echo 'Running simple admin interface' && sleep infinity"]
    networks:
      openvpn_net:
        ipv4_address: 10.20.0.3
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Status Page for OpenVPN (alternative simple interface)
  openvpn-status:
    image: auspexeu/openvpn-status:latest
    container_name: openvpn-status-page
    depends_on:
      - openvpn
    ports:
      - "8081:80"
    environment:
      - OPENVPN_STATUS_LOG=/var/log/openvpn/status.log
      - OPENVPN_MANAGEMENT_HOST=openvpn-server
      - OPENVPN_MANAGEMENT_PORT=7505
    networks:
      openvpn_net:
        ipv4_address: 10.20.0.4
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  openvpn_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/16
          gateway: 10.20.0.1

volumes:
  openvpn_data:
    driver: local
