version: '3.8'

services:
  # Main OpenVPN service
  openvpn:
    image: kylemanna/openvpn:2.4
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
      - "1194:1194/tcp"
      - "3005-3009:3005-3009/tcp"  # Port forwarding range
    volumes:
      - openvpn_data:/etc/openvpn
      - ./client_configs:/etc/openvpn/clients:ro
    environment:
      - OVPN_DATA=/etc/openvpn
      - OVPN_SERVER=10.8.0.0/16
      - OVPN_PROTO=tcp
      - OVPN_PORT=1194
      - OVPN_DNS=8.8.8.8,8.8.4.4
      - OVPN_MANAGEMENT=0.0.0.0 7505
      - OVPN_ROUTES=10.8.0.0/16
      - OVPN_NAT=true
      - OVPN_COMP_LZO=false
      - OVPN_CIPHER=AES-256-GCM
      - OVPN_TLS_VERSION_MIN=1.2
      - OVPN_TLS_CIPHER=TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384
      - OVPN_DUPLICATE_CN=false
      - OVPN_CLIENT_TO_CLIENT=false
      - DOCKER_USERNAME=${DOCKER_USERNAME}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
      - DOCKER_TOKEN=${DOCKER_TOKEN}
      - GH_TOKEN=${GH_TOKEN}
    networks:
      openvpn_network:
        ipv4_address: 10.8.0.1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pidof", "openvpn"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Simple Admin Panel for OpenVPN
  openvpn-admin:
    image: ruimarinho/openvpn-admin:latest
    container_name: openvpn-admin
    depends_on:
      - openvpn
    ports:
      - "8080:80"
    volumes:
      - openvpn_data:/etc/openvpn:ro
    environment:
      - OPENVPN_ADMIN_USERNAME=${OPENVPN_ADMIN_USERNAME:-admin}
      - OPENVPN_ADMIN_PASSWORD=${OPENVPN_ADMIN_PASSWORD:-admin}
    networks:
      openvpn_network:
        ipv4_address: 10.8.0.2
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Status Page for OpenVPN (alternative simple interface)
  openvpn-status:
    image: netzfisch/openvpn-status:latest
    container_name: openvpn-status
    depends_on:
      - openvpn
    ports:
      - "8081:80"
    environment:
      - OPENVPN_STATUS_LOG=/var/log/openvpn/status.log
      - OPENVPN_MANAGEMENT_HOST=openvpn
      - OPENVPN_MANAGEMENT_PORT=7505
    networks:
      openvpn_network:
        ipv4_address: 10.8.0.3
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  openvpn_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.8.0.0/16
          gateway: 10.8.0.1

volumes:
  openvpn_data:
    driver: local
